apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: frontandback
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.20
        imagePullPolicy: IfNotPresent
        name: front
      - image: praqma/network-multitool:alpine-extra
        imagePullPolicy: IfNotPresent
        name: back
        env:
          - name: HTTP_PORT
            value: "8080"
