all:
  hosts:
    cp1:
      ansible_host: 51.250.78.223
      ansible_user: yc-user
      #ip: 51.250.78.223
      #access_ip: 51.250.78.223
    node1:
      ansible_host: 62.84.118.156
      ansible_user: yc-user
      #ip: 62.84.118.156
      #access_ip: 62.84.118.156
    node2:
      ansible_host: 62.84.126.226
      ansible_user: yc-user
      #ip: 62.84.126.226
      #access_ip: 62.84.126.226
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
